/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComoTrabalhamosRouteImport } from './routes/como-trabalhamos'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as PerguntasFrequentesRouteImport } from './routes/perguntas-frequentes'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SobreNosRouteImport } from './routes/sobre-nos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoTrabalhamosRoute = ComoTrabalhamosRouteImport.update({
  id: '/como-trabalhamos',
  path: '/como-trabalhamos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasFrequentesRoute = PerguntasFrequentesRouteImport.update({
  id: '/perguntas-frequentes',
  path: '/perguntas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosRoute = SobreNosRouteImport.update({
  id: '/sobre-nos',
  path: '/sobre-nos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-trabalhamos': typeof ComoTrabalhamosRoute
  '/contactos': typeof ContactosRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/servicos': typeof ServicosRoute
  '/sobre-nos': typeof SobreNosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-trabalhamos': typeof ComoTrabalhamosRoute
  '/contactos': typeof ContactosRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/servicos': typeof ServicosRoute
  '/sobre-nos': typeof SobreNosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-trabalhamos': typeof ComoTrabalhamosRoute
  '/contactos': typeof ContactosRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/servicos': typeof ServicosRoute
  '/sobre-nos': typeof SobreNosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-trabalhamos'
    | '/contactos'
    | '/perguntas-frequentes'
    | '/servicos'
    | '/sobre-nos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-trabalhamos'
    | '/contactos'
    | '/perguntas-frequentes'
    | '/servicos'
    | '/sobre-nos'
  id:
    | '__root__'
    | '/'
    | '/como-trabalhamos'
    | '/contactos'
    | '/perguntas-frequentes'
    | '/servicos'
    | '/sobre-nos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoTrabalhamosRoute: typeof ComoTrabalhamosRoute
  ContactosRoute: typeof ContactosRoute
  PerguntasFrequentesRoute: typeof PerguntasFrequentesRoute
  ServicosRoute: typeof ServicosRoute
  SobreNosRoute: typeof SobreNosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-trabalhamos': {
      id: '/como-trabalhamos'
      path: '/como-trabalhamos'
      fullPath: '/como-trabalhamos'
      preLoaderRoute: typeof ComoTrabalhamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas-frequentes': {
      id: '/perguntas-frequentes'
      path: '/perguntas-frequentes'
      fullPath: '/perguntas-frequentes'
      preLoaderRoute: typeof PerguntasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nos': {
      id: '/sobre-nos'
      path: '/sobre-nos'
      fullPath: '/sobre-nos'
      preLoaderRoute: typeof SobreNosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoTrabalhamosRoute: ComoTrabalhamosRoute,
  ContactosRoute: ContactosRoute,
  PerguntasFrequentesRoute: PerguntasFrequentesRoute,
  ServicosRoute: ServicosRoute,
  SobreNosRoute: SobreNosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
